export const PROJECT_VERSION = '1.0.4'
export const LOCAL_STRATEGY = 'local'
export const JWT_STRATEGY = 'jwt'
export const SEQUELIZE = 'SEQUELIZE'
export const DEVELOPMENT = 'development'
export const TEST = 'test'
export const PRODUCTION = 'production'
export const PASSWORD_FIELD = 'password'
